spring:
  data:
    mongodb:
      username: albert
      password: albert
      host: localhost
      port: 27017
      database: customerdb
      authentication-database: admin

server:
  port: 8090





